### ISSUE TITLE
Format numbers

### ISSUE THREAD

**Issue by Anexes** [IdleLands/Play#125]
Pretty much all numbers could really use to be formatted. Especially in statistics and combat, where you often see numbers with 6-8 digits.

For the sake of clarity, this is what I mean: `468185112` -> `468,185,112`

**Comment by seiyria** [comment]
It'll be tough to do this in combat, as that comes from the server (you may want to open an issue over there for it, since it's partially done there for things like achievements), but I'll be adding this everywhere else that needs it.
