### ISSUE TITLE
pet upgrade cost display possibly incorrect?

### ISSUE THREAD

**Issue by seiyria** [IdleLands/Play#126]
Kold, the Sponge Nov 8, 2016, 12:57:33 PM Mod; IP|216.16.8.13
It was the pet upgrade issue, where you could spend more gold on pet upgrades than what you actually have
Kold, the Sponge Nov 8, 2016, 12:57:45 PM Mod; IP|216.16.8.13
I had 100,006 gold, opened the ability to purchase the Gold Bonus upgrade on my pet rock. I bought it, and only 10,000 gold was used from what I had
Kold, the Sponge Nov 8, 2016, 12:57:49 PM Mod; IP|216.16.8.13
I was left with 90,006 gold

**Comment by JoeSyr** [comment]
I don't think I was actually charged for any of my digipet upgrades, whereas the feeding costs seemed to go in right away. Was camping during the whole time, perhaps that contributed to the bank error in my favor.
