### ISSUE TITLE
Character copies appear on map

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Play#32]
http://puu.sh/pU5xl/55a24f9b4d.png

If you hover over the real you and the ghost you, they both have your information. It lasts for a few seconds, then disappears. Then the next tick happens a few seconds later and it repeats. Not sure if you can see the same effect in other players, I'm not near anyone on the map at the moment.

**Comment by seiyria** [comment]
I can't personally repro this at this time but I'll leave this open for a while.

**Comment by sedgwick** [comment]
I believe this is something that occurs when the game has been running for an extended time. I was seeing it this morning after the game ran all night. It was a little shorter than the first time I reported the issue. After closing the tab and opening a new one, I was seeing no clone. I'll let the game run for awhile again and see if it appears later.

**Comment by sedgwick** [comment]
Only your character creates clones when moving on the map.

http://puu.sh/pZCTP/c224cc8dcb.png

In this image are 4 players. The clone is south of the highlighted character, but when moving none of the others create a copy.

**Comment by sedgwick** [comment]
Haven't seen it after letting the game run for about 9 hours. It would usually happen much sooner, so this seems fixed now.

**Comment by seiyria** [comment]
Sounds good.
