### ISSUE TITLE
New map does not load when on map tab

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Play#34]
http://puu.sh/q1xbb/230dbb560c.png

Moved from norkos to the boathouse -1. The map goes black for a second, but then comes back up as the norkos map. Text for the new map loads though. Changing tabs and coming back loads the proper map.

**Comment by seiyria** [comment]
I think this is a periodic issue, because it doesn't seem to happen for me all the time.

**Comment by sedgwick** [comment]
I haven't noticed it in awhile, have you? Is it possible other changes have corrected this?

**Comment by seiyria** [comment]
You never know. I'll close it for now, and if it comes back it can be addressed later.

**Comment by sedgwick** [comment]
Ask and you shall receive: http://puu.sh/qM3Ag/0fca47ca67.png

Hit the teleporter on dark tower -3, and -3 loads again instead of -2. Dark Tower -2 is a small map, so I stayed on the map tab until it took me up to -1 and it loaded the -2 map.

http://puu.sh/qM3Yx/fcb43eb396.png

**Comment by seiyria** [comment]
Ill be pushing a small change later. Feel free to reopen for the time
being.

**Comment by seiyria** [comment]
Ane is reporting that it does load the correct map after a delay. This might need some new confirmation with the slight map code changes I made.

**Comment by sedgwick** [comment]
My results are similar after I teleported around a few times It has the initial lag of loading a new map, and that's at least to be expected.

**Comment by seiyria** [comment]
Closing for now, since it seems(?) to be resolved.

**Comment by sedgwick** [comment]
This appears to still be possible. I hit the teleporter in the Lich Brother's Mansion and was sent back to Norkos, but it reloaded the Lich Brother's Mansion map. Personalities make it hard to see but you can see it has Norkos up in the corner.

**Comment by seiyria** [comment]
bollooooooooooooocks. I still wonder if this was lag, though. I'll reopen it for now...

**Comment by sedgwick** [comment]
For future reference, how long should I wait before switching tabs to see if it is lag? I believe it was at least 60 seconds, since I was getting a screenshot submitted and writing up the issue.

**Comment by seiyria** [comment]
this will no longer be a problem with beta
