### ISSUE TITLE
Typing in chat slows to a crawl sometimes

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Play#37]
Using Firefox. Not sure what causes this to happen. The only time I can get it to happen is clicking the Global Events channel when it is very full (leaving the game on overnight) and then try typing in the chat box. My only other guess is it might be related to how much text is available to scroll through. For example, tonight I was working on Norkos Dungeon maps, so there was a lot more activity with no refresh. Out of nowhere the text slowed to a crawl. Tomorrow I'll test the global events method to see if it still happens that way.

**Comment by sedgwick** [comment]
Opened global events after letting it build up over night. Had a notification of 2700+ and it was hanging for about 5 seconds after clicking. Typing in the chat was very slow, to the point I just force closed it because it makes the browser buttons unresponsive while it slowly entered my test text.

**Comment by seiyria** [comment]
Yep. So, to be clear, it's definitely global events? We have a few options then:

* add a toggle to turn off global events
* add a "clear chat" button (or something of that ilk)
* ???

What would work for you?

**Comment by sedgwick** [comment]
http://pastebin.com/eX9SNQvP

After about 15 minutes on overview, I clicked back to chat tab. https://puu.sh/qiFRs/ffaa7f2c6e.png
That's 123 notifications in the global events log, which is a little more but they could have popped up in the few seconds in between the screenshot and clicking over. So, the log is holding more than 50, but only if you come back to the chat tab. the only reason I think it can happen in general is if someone was talking a lot in general while you were tabbed out, similar to general events, or if you stay in general and your local log builds up, and possibly holds more than 50. When I have some time later, maybe we can test it in a private message. you just spam my PM and we see if it builds up locally more than 50 and I can also try typing while you do it to see if it's getting slower.

**Comment by sedgwick** [comment]
So it isn't that typing in the game is slow. Loading the chat tab with a high amount of entries causes each window/tab of the browser to be slow to respond. I was typing some stuff in another window and it was lagging there too. 

I can't seem to replicate it through PM. Maybe it's the size and not the quantity, as I was sending small text from a test account. It remembers the last 10 messages when you come back, but as long as you stay on the tab while talking it will just keep everything, not the last 50. Right now I'm just sitting with the global events tab open. I can type normally at the beginning, so going to just try a few test lines every once in awhile to see if it can occur while on it, or if it is an issue of loading the large amount of entries all at once that causes it to stay laggy.

**Comment by seiyria** [comment]
I think I found why it bypasses the 50 limit. Working on a fix.
