### ISSUE TITLE
Private Messages display incorrectly

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Play#38]
I received a private message and in the chat channels bar, it said the message came from me, not the other user. So I click it and it says the other user in the chat section saying hi. The bar below says "send a message to sedgwick" and saying hello back sends me a private message. That private message shows up in the chat channel bar from the other user, and in that one I can send a message to him. http://puu.sh/qlxVV/cc7b5b2996.png

**Comment by seiyria** [comment]
If this happens again, here are steps to get the data for me to look at:

* open the console (hit f12)
* type `window.localStorage['idp-chatData']`
* copy that data into a pastebin or something.

**Comment by seiyria** [comment]
this happens more frequently when you are not on the chat tab and receive a message.
