### ISSUE TITLE
Personalities window cannot be dragged on FireFox.

### ISSUE THREAD

**Issue by Souzooka** [IdleLands/Play#77]
I cannot drag the personalities window which appears on the map in FireFox. Just tested this to see if I would have the same issue on Chrome; it seems that while I can drag the window just fine on Chrome, on FireFox the window cannot be dragged.

**Comment by seiyria** [comment]
@sedgwick was telling me about this earlier. I'll get at this as soon as I can, because I plan to use draggable windows more for other things, later on.

**Comment by seiyria** [comment]
dear future me, firefox is fucking awful: https://bugzilla.mozilla.org/show_bug.cgi?id=505521

gotta find a way around this.

**Comment by seiyria** [comment]
will no longer be an issue
