### ISSUE TITLE
pets don't feed selves: pet smart-self is broken

### ISSUE THREAD

**Issue by sidawson** [IdleLands/Play#98]
I've waited through several "find item" cycles. Plenty of cash. No self-feeding. Pet stays on old level (despite me having gone up a level half an hour ago). I stayed on the pet page for 20 mins or so, no dice.

[not sure if this is front or back end issue]

**Comment by seiyria** [comment]
pets do not feed themselves, they only upgrade themselves.

**Comment by sidawson** [comment]
Ahh, then the mouseover message on Smart Self might need some tweaking. It currently says "Automatically upgrade self if enough gold". I took this to mean upgrade levels. Particularly since Smart Equip says "Automatically unequip items with the lowest score" - which would seem to be in very much the same ballpark of behaviour.

Perhaps "Automatically upgrade gear if enough gold" - but then, how can it do that without unequipping lower items - except right when you first get the pet? Also, how does gold factor into it? Doesn't the pet **find** items? In which case, it doesn't need gold to purchase them.

In which case, a single "Smart Equip" with "Automatically improve gear, if enough gold" might suffice for both activities (if gold is actually a factor).

Small things, I admit, but it'll clarify those options a ton.

**Comment by seiyria** [comment]
It doesn't upgrade it's own gear either. It only upgrades itself, ie, max gold, all that stuff. The... upgrades section.
