### ISSUE TITLE
idle.land security cert has expired

### ISSUE THREAD

**Issue by sidawson** [IdleLands/Play#99]
The SSL cert from bitballoon appears to have expired.

This then brings up error messages in certain browsers, when navigating to the site.

example here: https://puu.sh/rcGc9/faf71151da.png

(sorry, couldn't upload for some reason)

**Comment by seiyria** [comment]
I, uh, don't have a SSL cert. I don't enforce or use https. Until I do this is a non-issue. I have an issue open for HTTPS on Play.
